on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'
      - run: |
          go version

      - name: download go mod
        run: |
          go mod download

      - name: go build
        run: |
          go build .

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "go-clicli"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: echo "🥳"
