on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'
      - run: |
          go version
      - name: download go mod
        run: |
          go mod download
      - name: go build
        run: |
          go build .
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "go-clicli"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: echo "🥳"

      - name: Build Image
        env:
          DockerUsername: ${{ secrets.DOCKER_USERNAME }}
          DockerPassword: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DockerUsername -p $DockerPassword
          docker build -t yisar/clicli_api .
          docker push yisar/clicli_api
  deploy:
    runs-on: ubuntu-latest
    needs: [publish]
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: 22
          script: |
            docker pull yisar/clicli_api
            docker-compose up -d  